### ISSUE TITLE
When I split the WebPack to two files - Error Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry

### ISSUE THREAD

**Issue by msbasanth** [web-padawan/lit-components#38]
Hi,

When I split the WebPack to two files and tried import both the files in index.html. I am getting an error what could be the reason behind? I have the commons going to vendor.js.

`
dom-module.js:163 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at Module../node_modules/@polymer/polymer/lib/elements/dom-module.js (http://10.83.44.18:8080/dropdown.js:5270:16)
    at __webpack_require__ (http://10.83.44.18:8080/dropdown.js:20:30)
    at Module../node_modules/@polymer/polymer/lib/utils/style-gather.js (http://10.83.44.18:8080/dropdown.js:19191:81)
    at __webpack_require__ (http://10.83.44.18:8080/dropdown.js:20:30)
    at Module../node_modules/@polymer/polymer/lib/mixins/element-mixin.js (http://10.83.44.18:8080/dropdown.js:9050:80)
    at __webpack_require__ (http://10.83.44.18:8080/dropdown.js:20:30)
    at Module../node_modules/@polymer/polymer/polymer-element.js (http://10.83.44.18:8080/dropdown.js:20310:86)
    at __webpack_require__ (http://10.83.44.18:8080/dropdown.js:20:30)
    at Module../packages/drop-down/sh-icon.js (http://10.83.44.18:8080/dropdown.js:23990:93)
    at __webpack_require__ (http://10.83.44.18:8080/dropdown.js:20:30)
`

Regards
Basanth

**Comment by web-padawan** [comment]
Hi. This is a limitation of Polymer that is used by styles packages.
You should make sure the `dom-module` or any other custom element is not imported twice.

Also, note that this repo is an experiment and is not currently maintained.

**Comment by msbasanth** [comment]
Hi @web-padawan ,

Struggling to avoid importing the custom elements twice in my code base.
Tried using a hack provided for deduping but didn't work as it started giving some layouting issues (https://www.npmjs.com/package/@lrnwebcomponents/deduping-fix).

How did you package vaadin controls in separate JS files and we are able to import it separately in index.html?
Could you please give a link to proceed?

Regards
Basanth
